### PR TITLE
Added BG Queue Hopping Countermeasures.

### PR DESCRIPTION
**Pull request by Anteara**
Notes:
I tested this on my own local environment. It works flawlessly.
But, I bet once we post it to the live server it will crash it, and cause hell to raise,and the four horsemen will destroy the world and the sun will supernova and destroy the earth.

Also, before migrating this --POST AN ANNOUNCEMENT so people don't get upset they can't dodge the queue anymore.

### CODE REVIEW

**Comment by honeyhoney** [comment]
Is BG queue hopping an issue?

**Comment by Anteara** [comment]
yeah according to some ppl it puts off people from queuing even if it doesnt happen at that moment, 
the problem is self inflicting, knowing it is there makes it worse by default

**Comment by Anteara** [comment]
Ok, I'll speak coherently this time.
What I mean by that is queue hopping has 2 negative side effects
1) The BG itself is now non-playable.
2) Those people are now no longer going to queue for a BG, because they fear it happening again.

My idea is that if we remove (2), we also remove (1), therefore we can improve PvP by (reluctantly) forcing a BG to remain in progress.

**Comment by honeyhoney** [comment]
Personally I've always enjoyed the fact that I can queue for both AB and WSG, AB starts, there's only like 4 people in it, suddenly, WSG pops up and you have a decent 6v6 or so. (particularly as battlegrounds are like buses, you queue for 1 for 20 minutes, suddenly 5 come along all at once)
Worth discussing with the team whether this is something we want to add.

**Comment by AnonXS** [comment]
I am personally for implementing Queue Drop, Hellground did it too recently. We want competetive Battlegrounds not Battleground hopping as soon as you seem to loose a battleground and a new one opens.

**Pull request merged**
