### PR TITLE
Create 044_Updates_04.08.16.sql

### PR DESCRIPTION
**Pull request by AnonXS**

### CODE REVIEW

**Comment by robinsch** [comment]
Don't use delimiters around numeric data! http://dev.mysql.com/doc/refman/5.6/en/type-conversion.html

**Comment by Pbeitelmann** [comment]
I agree, please set all Values to appropriate data types. You can use "DESCRIBE table" to get the datatype of each columns.  

e.g.

UPDATE `creature_template` SET `equipment_id`='8019',`mechanic_immune_mask`='346100947',`mindmg`='1337',`maxdmg`='1762'

should be

UPDATE `creature_template` SET `equipment_id`=8019,`mechanic_immune_mask`=346100947,`mindmg`=1337, `maxdmg`=1762

**Comment by RobinWW** [comment]
updated pls http://pastebin.com/Jc7YtqDF

**Comment by Xadras** [comment]
I guess the delimiters are automatic added by old-shitty navicat, I noticed it from my own copied querys there, too. Also it is currently not a very big deal - but a nice to change.

**Pull request merged**
