### PR TITLE
Core/Spells: Holy spells should have a 100% hit chance before modifiers.

### PR DESCRIPTION
**Pull request by AbaddonL4G**
credits to robinsch (TBCPvP)

### CODE REVIEW

**Comment by tst12** [comment]
similar like a [fix ](https://github.com/Looking4Group/L4G_Core/pull/3493)for https://github.com/Looking4Group/L4G_Core/issues/2688
its  just broke
http://wowwiki.wikia.com/wiki/Magic_schools_(WoW)?oldid=1036356

> It is not possible to build resistance to Holy magic, giving Holy Priests an advantage over other casters, but all characters and mobs do have a base resistance chance

> In PvE, Holy resistances do exist under specific circumstances (if the enemy has a higher level than you), and in that case your Holy spells may be partially resisted. 

http://wowwiki.wikia.com/wiki/Holy_resistance?oldid=1375515
> Players and monsters come with a base chance to resist Holy damage, and that is it! The sole means to prevent holy damage are limited to effects that affect all spells, like reduction (e.g. Potions) and immunity (e.g. Divine Intervention).

**Comment by AbaddonL4G** [comment]
thats why a "100% hit chance before modifiers" sounds legit to me.
tbh there is no real source but atm the resist chacne is way to high

**Comment by tst12** [comment]
after this commit every spell have "100% hit chance before modifiers -  base resistance chance" as expected and only holy havent

**Comment by AbaddonL4G** [comment]
so gonna close this one since it seems to be incorrect

**Comment by robinsch** [comment]
It's correct. No idea what ts12 saying.

**Comment by tst12** [comment]
https://github.com/Looking4Group/L4G_Core/blob/baa4a2d4333e43f6235ce67b4bda9ae9aa78af7c/src/game/Unit.cpp#L3081-L3090

.... bold it again
http://wowwiki.wikia.com/wiki/Magic_schools_(WoW)?oldid=1036356
> **but all characters and mobs do have a base resistance chance**

http://wowwiki.wikia.com/wiki/Spell_hit?oldid=1247552
http://wowwiki.wikia.com/wiki/Precision_(Paladin_talent)

> Precision` (Protection) **now increases spell hit chance** as well, stacking with spell hit rating in spellcasting

you think blizz are stupid?

**Comment by AbaddonL4G** [comment]
http://wowwiki.wikia.com/wiki/Resistance#Spell_resist_mechanic
There was no resistance stat for Holy, and as such no players nor NPCs could resist Holy spells. 


http://wowwiki.wikia.com/wiki/Holy_resistance?oldid=1375515
Resistable Spells
Paladin: 8 Judgements, Consecration, Hammer of Wrath, Holy Shock, Avenger's Shield, Repentance, Crusader Strike, Holy Wrath, Exorcism, Turn Undead, Turn Evil
Priest: Smite, Holy Nova, Dispel Magic, Mass Dispel

**Pull request closed without merging**
