### PR TITLE
Fixed : DoT and Faerie fire now both properly remove stealth 

### PR DESCRIPTION
**Pull request by TrenchFox**
All DoT and Faerie fire will now remove stealth on their application.

DoT would only happen on first tick,

Faerie fire wouldnt let you RE-stealth, however it would allow you to stay stealthed until knocked out.

### CODE REVIEW

**Comment by AbaddonL4G** [comment]
FF is allready fixed?
gonna test today maybe dunno if i got time (germany soccer beer)

**Comment by TrenchFox** [comment]
I dont submit fixes that wern't tested....

Please accept the pull request all of the issues were tested with Buscha and Anonx

**Comment by AbaddonL4G** [comment]
This branch has conflicts that must be resolved.
Use the command line to resolve conflicts before continuing.

**Comment by AbaddonL4G** [comment]
We can’t automatically merge this pull request. 
Can't merge from smartphone :P

**Comment by Evolvee** [comment]
Basically everything that triggers combat -.- except mass dispel(not sure if MD should trigger combat or not, but at the end of the day the result should be same)

**Pull request merged**
