### PR TITLE
Black Morass Post-Event Update and hopefully fix for quests not always completing

### PR DESCRIPTION
**Pull request by Saltgurka**
https://bitbucket.org/Caboon/playcore-official/commits/04472a6cca50fb671f0e24604d5e603ffa38fb96

Tested locally

### CODE REVIEW

**Comment by Rushor** [comment]
The endevent itself is missing :(

**Comment by Saltgurka** [comment]
Which event are you referring to? This PR includes the orcs running through the portal etc. (https://youtu.be/_-rJEeA_dIc?t=15m15s)

**Comment by AbaddonL4G** [comment]
https://travis-ci.org/Looking4Group/L4G_Core/builds/183010444

Why does it fail?

**Comment by Rushor** [comment]
@Saltgurka oh nvm, didn't saw it the first time. Thanks for this huge change!

**Pull request merged**
