### PR TITLE
Leotheras ww stack

### PR DESCRIPTION
**Pull request by AbaddonL4G**
leotheras should be more challenging with ww dbuff stacking twice.

!!!NOT BLIZZLIKE!!!

### CODE REVIEW

**Comment by AbaddonL4G** [comment]
fucked up sec...........

**Comment by robinsch** [comment]
This won't work at all. You are trying to add stacks to something that isn't a aura at all.

**Comment by AbaddonL4G** [comment]
i tested it local it worked...................
but bth not blizzlike so i closed the pr..

**Comment by AbaddonL4G** [comment]
but btw: pr was fucked up dunno why i am not that into the whole git thing.
changed code was

`            case 37641: // leo ww stack
                spellInfo->StackAmount = 5;
                break;`

**Pull request closed without merging**
