### PR TITLE
Fixes an issue where Neutral mobs can attack, when logic states they...

### PR DESCRIPTION
**Pull request by Anteara**
…shouldn't be able to initiate attack. Consider Atummen The Huntsman in Karazhan.

Reproduce: BEFORE FIX:
Go to Attumen in Kara.
Stand 25 yards away. Right click him (Raise your weapon, i.e. ready to attack)
Continue to walk forward
He will attack YOU, when you are CLEARLY out of melee range. You are still 20 yards away yet he (a neutral NPC) will attack you.

AFTER FIX:
Do as above,
He will NEVER attack first, so right click, and keep moving forward. Only AFTER you melee hit, will he aggro.

### CODE REVIEW

**Comment by Rushor** [comment]
```c++
bool Creature::CanStartAttack(Unit const* who, bool force) const
{
    if (IsCivilian())
        return false;

    // This set of checks is should be done only for creatures
    if ((HasFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC) && who->GetTypeId() != TYPEID_PLAYER)                                   // flag is valid only for non player characters
        || (HasFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC) && who->GetTypeId() == TYPEID_PLAYER)                                 // immune to PC and target is a player, return false
        || (who->GetOwner() && who->GetOwner()->GetTypeId() == TYPEID_PLAYER && HasFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC))) // player pets are immune to pc as well
        return false;

    // Do not attack non-combat pets
    if (who->GetTypeId() == TYPEID_UNIT && who->GetCreatureType() == CREATURE_TYPE_NON_COMBAT_PET)
        return false;

    if (!CanFly() && (GetDistanceZ(who) > CREATURE_Z_ATTACK_RANGE + m_CombatDistance))
        //|| who->IsControlledByPlayer() && who->IsFlying()))
        // we cannot check flying for other creatures, too much map/vmap calculation
        /// @todo should switch to range attack
        return false;

    if (!force)
    {
        if (!_IsTargetAcceptable(who))
            return false;

        if (who->IsInCombat() && IsWithinDist(who, ATTACK_DISTANCE))
            if (Unit* victim = who->getAttackerForHelper())
                if (IsWithinDistInMap(victim, sWorld->getFloatConfig(CONFIG_CREATURE_FAMILY_ASSISTANCE_RADIUS)))
                    force = true;

        if (!force && (IsNeutralToAll() || !IsWithinDistInMap(who, GetAttackDistance(who) + m_CombatDistance)))
            return false;
    }

    if (!CanCreatureAttack(who, force))
        return false;

    // No aggro from gray creatures
    if (CheckNoGrayAggroConfig(who->getLevelForTarget(this), getLevelForTarget(who)))
        return false;

    return IsWithinLOSInMap(who);
}
```

**Comment by Anteara** [comment]
Hi Rushor, thanks, do you think this function you posted would have better stability / efficiency / less bugs or something than the current one?

Thanks.

**Comment by Rushor** [comment]
the version i posted is from trinitycore and works very well. maybe you find some further addition that could be added to the L4G Core. Cheers :)

**Comment by honeyhoney** [comment]
Awesome, thanks. We'll be sure to go through it.

**Pull request merged**
