### PR TITLE
Core/Collision: LoS check for M2 Models

### PR DESCRIPTION
**Pull request by AbaddonL4G**
credits to TC: https://github.com/TrinityCore/TrinityCore/commit/c53d722aa29ff3a39d881de7d6ef86b79deffe48

and to xadras (some features allready included to remove special maps from this check)

### CODE REVIEW

**Comment by AbaddonL4G** [comment]
should fix https://github.com/Looking4Group/L4G_Core/issues/3071 and all related issues.

Everything tested (including the restriction for WS)

**Comment by AbaddonL4G** [comment]
Problem: able to blink into those objects if actiaved.

**Comment by robinsch** [comment]
Nooo, this will ignore all pathfinding when it comes to M2 objects.

**Comment by AbaddonL4G** [comment]
so basically in your tbcpvp core its also false?

        // M2 models are not taken into account for LoS calculation
        if (Flags & 1)
            return false;

**Comment by robinsch** [comment]
Yes

**Comment by AbaddonL4G** [comment]
solution would be to split the whole function for pathfinding and using spells and implement this check only at the spell function?

**Comment by robinsch** [comment]
just add a additional parameter to functions and you are fine. I'm using this for ages on blizzlike servers.

**Comment by AbaddonL4G** [comment]
https://github.com/cmangos/mangos-tbc/commit/68fdd1e578102e274c8c85e14c717ebf569d2e61

**Pull request merged**
