### PR TITLE
Void Reaver Knockback - Threat Reduce

### PR DESCRIPTION
**Pull request by AnonXS**
http://www.excalibur-nw.com/forum/tracker/issue-2376-void-reaver/

https://elitedelwow.wordpress.com/2008/09/16/boss-void-reaver/

http://www.worldofstrats.com/VoidReaver/tabid/62/Default.aspx

http://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-guides/15038-void-reaver-strategy-guide.html

### CODE REVIEW

**Comment by AbaddonL4G** [comment]
Maybe Bit heavy? We had 3tanks +ss on fury (Fury died all the time).
Think it needs to ne tested with -25%

**Comment by AnonXS** [comment]
yea i think it might be a little much too, but as the aggro reduce is bound to the spell it only applies if the spell hits, i dont know whether the knockback spell can be dodged etc. From feeling i would say about 15-20% is enough.

**Comment by AbaddonL4G** [comment]
Y it was like first knockback still 1st tank and after 2nd to 3rd knockback The tank "rotated"

Not easy to check if its too much without a 10+man raid.

**Comment by AnonXS** [comment]
So do we want to start at a lower value? I think we spoke with someone who mentioned 14%.

**Comment by AbaddonL4G** [comment]
Doesnt matter just start with a value on ptr let The raids test.
If 25% is possible (but needs extra time vor tanks etc) => perfect.

But its important to change it during the ptr testing phase

**Pull request merged**
