### PR TITLE
Fixed : Lifebloom now Blooms when displelled

### PR DESCRIPTION
**Pull request by TrenchFox**
Also added support from Robinsch to eventually be able to calculate damage needed to break fear/roots

### CODE REVIEW

**Comment by robinsch** [comment]
The dummy aura should handle this.

**Comment by abuescher** [comment]
I did the tests on ptr, bloom works. No further testing needed. 

Cheers, Buscha

**Comment by TrenchFox** [comment]
Sucks that there are no PM's through Github. @robinsch I appreciate the work you do for the community, do you have somewhere where we could chat?

**Comment by robinsch** [comment]
You can find me on the trinitycore IRC channel.

**Comment by TrenchFox** [comment]
Got commit access, going to fix styling and commit myself.

**Pull request closed without merging**
