### PR TITLE
Core/Spell: Environmental Damage in combat

### PR DESCRIPTION
**Pull request by AbaddonL4G**
Environmental Damage  from Bonfires/Campfires and so on no longer put u
in combat

### CODE REVIEW

**Comment by AbaddonL4G** [comment]
Working cause Environmental Damage is selfcast:
https://github.com/Looking4Group/L4G_Core/blob/master/src/game/SpellEffects.cpp#L298

Tested on local system.

**Comment by Rushor** [comment]
do you have a source that Environmental Damage should not put you in combat?

**Comment by AbaddonL4G** [comment]
Currently no perfect source.
But since Falldamage and lava (also fire from environment?) should not put you in combat:
https://www.youtube.com/watch?v=2q0oEJjCsZI

Possible source: https://www.youtube.com/watch?v=r9SKhDYC05o

**Comment by AnonXS** [comment]
http://wow.gamepedia.com/index.php?title=Stealth&direction=next&oldid=1873946 - 22 May 2009

http://wowwiki.wikia.com/wiki/Stealth?direction=next&oldid=1873946 - 22 May 2009

Stealth no longer is broken due to falling damage, unless of course it kills the stealth unit. However, fire damage from camp fires will still reveal it.

Stealth and Falldamage was patched in early wrath, fires still break stealth in tbc.

http://www.wowhead.com/forums&topic=123232/fall-damage

By pnukup (5,835 – 1·11·32) on 2008/12/21 (Patch 3.0.3)		
I think fall damage no longer break stealth.
I was in rank 1 stealth and took 12 fall damage and I did not get out of stealth.

**Comment by AbaddonL4G** [comment]
mhm looks like it should put u in combat?
and make a bit dmg.

stupid :D

**Comment by AbaddonL4G** [comment]
Is there a real use in pvp for fires breaking stealth?
i mean we literelly got no open world pvp at places like OG.

I think its a stupid mechanic and blizz removed it from the game (patch 3.x) for a good reason.

**Comment by AnonXS** [comment]
The damage component works on cmangos.

**Pull request closed without merging**
