### PR TITLE
Global cooldown<=1500,>=1000;

### PR DESCRIPTION
**Pull request by AnonXS**
https://github.com/robinsch/TBCPvP/commit/15f7a636500f0eeb79dd470d7669bc533d33b798

https://bitbucket.org/looking4group_b2tbc/looking4group/issues/1227/cast-slowing-curses-effects-affect-global

### CODE REVIEW

**Comment by AbaddonL4G** [comment]
tested?
never noticed a bug with this

**Comment by Evolvee** [comment]
his fix on smolderforge just normalized gcd, but when u cast icy veins/haste trinkets, you should get lower gcd however u will still get the normalized max value when afflicted by curse of tongues/mind numbing poison... so u can feel the difference in GCD

**Comment by robinsch** [comment]
This is also fixed in a newer commit at TBCPvP

**Comment by Rushor** [comment]
https://api.github.com/users/xxxxxxx/events/public
git commit --amend --author "authorsname <authorsemail>"

**Pull request merged**
