### PR TITLE
Create 051_U_23.08.16.sql

### PR DESCRIPTION
**Pull request by AnonXS**

### CODE REVIEW

**Comment by robinsch** [comment]
And again ' strikes!

**Comment by AnonXS** [comment]
tables convert it properly, never had any problem except for defined SET XYZ := 'Number';

I will take out all 'IN' in the future but '' makes it alot easier to work with as double clicking doesnt mark spaces too when the number is ''.

**Comment by robinsch** [comment]
I posted links where the issue was described, if this is not present for you doesn't mean it isn't for others ...

**Comment by robinsch** [comment]
Also there are settings to edit what gets marked by double clicking at most ide or text editors

**Comment by AnonXS** [comment]
Is this form any better? (`entry`='-673'); seeing this alot.

**Comment by robinsch** [comment]
No

**Comment by AnonXS** [comment]
thought so. makesmefeelbetter, i will work on it, maybe i can change some programm settings to make the programm do what i want it to do in order to write in correct format, without loosing comfort in working with it.

**Pull request merged**
