### PR TITLE
Updates to fear and root damage breaking

### PR DESCRIPTION
**Pull request by Saltgurka**
It should now break much more frequently than it is currently.

This needs extensive testing before going live. Preferably we should ask some pvp players to come on PTR and help us out.

I have tested it locally and it seems to work ok. I'm not a pvp player though so I don't know how frequently fear generally breaks.

Credits to TBCPvP.

### CODE REVIEW

**Comment by Saltgurka** [comment]
So there is a minor flaw with this. currentDamage is only reset after the fear/root is removed by damage. It should be reset on aura expire as well. The way it works now, you could work your way up to a high currentDamage number, you were unlucky that the fear was not broken, and then the next time you get feared your currentDamage would still be the same resulting in a much higher chance that it gets removed instantly.

I'm not sure how to solve this, but it is a rather minor issue I would say

**Comment by anonxy** [comment]
Why dont you port all of the commits from @robinsch so you dont have to wait till anyone makes a bugreport.

**Comment by robinsch** [comment]
You neee to reset the counter at EffectModRoot/Fear for apply = false case and remove it from the current function

**Comment by Saltgurka** [comment]
Thanks @robinsch  :)

**Comment by Saltgurka** [comment]
I created a new PR with the changes: https://github.com/Looking4Group/L4G_Core/pull/3074

After upgrading to VS15 I forgot to set tabs to spaces, so it messed it up :(

**Pull request closed without merging**
