### PR TITLE
Diminishing Returns - No DR on Slow Spells

### PR DESCRIPTION
**Pull request by AnonXS**
http://looking4group.eu/hellfire/showthread.php?tid=1565

https://bitbucket.org/looking4group_b2tbc/looking4group/issues/415/diminishing-returns

### CODE REVIEW

**Comment by AnonXS** [comment]
Wenn alles nichts hilft lieber nochmal auf Anfang und wir testen das komplett local durch.

https://bitbucket.org/looking4group_b2tbc/looking4group/src/d9e91f108059a52a106e99160c899eea56e944ab/src/game/SpellMgr.cpp?at=master&fileviewer=file-view-default

**Comment by AbaddonL4G** [comment]
fixed the nova/poly/slow bug but controlled stuns like hammer of justice still share dr with uncontrolled stuns.

**Comment by AnonXS** [comment]
ok controlled stuns are all uncommented try commenting them or should modify and push again?

**Comment by AbaddonL4G** [comment]
create new pull with commenting them please 
github shows conflict with this pull.

https://www.youtube.com/watch?v=LCAWt54PwdA

**Comment by AnonXS** [comment]
Fixing Conflict & Comment In Controlled Stuns

**Comment by Schaka** [comment]
Didn't fix the conflict. There are still >>>>>HEAD strings in the files.
This won't compile.

**Comment by AbaddonL4G** [comment]
changed typo - compile working.
testing dr now.
will upload video.

**Comment by AbaddonL4G** [comment]
so: mace specc stun + SH stun dont share DR if triggered by autoattack.
i think my old proof vid is fail cause i trigger the stun procc spell manually.
will merge anyways cause mage poly/nova/slow is fixed. if other bugs occur => total revert.

**Comment by AnonXS** [comment]
spell casted by item - needs triggered flag.

**Comment by AbaddonL4G** [comment]
got vids cant upload atm cause of crappy hotspot

**Comment by AnonXS** [comment]
return DIMINISHING_LIMITONLY;

Should be

return DIMINISHING_ENSLAVE; 

for Enslave Demon

**Pull request merged**
