### PR TITLE
Update SpellMgr.cpp

### PR DESCRIPTION
**Pull request by AnonXS**
Resolves https://bitbucket.org/looking4group_b2tbc/looking4group/issues/2574/limited-invuln-belt-usable-in-arena

### CODE REVIEW

**Comment by robinsch** [comment]
There should be a itemflag that prevent those items from being used in arena.

**Comment by AnonXS** [comment]
ITEM_FLAG_USEABLE_IN_ARENA - http://www.wowhead.c...155;crs=1;crv=0 these are only items usable in arena. try to get any other consumable item and use it during arena match.

But we want ITEM_FLAG_NOT_USEABLE_IN_ARENA.

**Comment by robinsch** [comment]
Woops, my bad.

**Comment by robinsch** [comment]
Then it should be implemented. Atleast Rocket Boots has this flag in TBC. And I don't know about other items that should not be used in arena. The belt was always usable in arena, even in S4.

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/141

**Comment by robinsch** [comment]
So what? It's a fun server.

2.3.2 Patch notes:
"Rocket Boots Xtreme and Rocket Boots Xtreme Lite can no longer be used in the arena. These no longer have a failure chance."

This is the only proof you have, I posted claims above.

**Comment by AnonXS** [comment]
Guess you are right, we should leave them in, uncommented, until the respective patch is reached.

**Comment by robinsch** [comment]
I would rather make a @todo comment above all those that states that they should be removed when something right is implemented (which you can find on public repos)

**Pull request closed without merging**
