### PR TITLE
fix quest 10672

### PR DESCRIPTION
**Pull request by tst12**
check with
https://github.com/Looking4Group/L4G_Core/pull/3547
https://github.com/Looking4Group/L4G_Core/pull/3548

### CODE REVIEW

**Comment by tst12** [comment]
db part
```

DELETE FROM creature  WHERE id=21924;

INSERT IGNORE INTO `creature` (`guid`, `id`, `map`, `spawnMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`) VALUES
(,'21909','530','1','0','0','-3414.29','813.942','-31.1204','1.47848','30','3','0','1','0','1'),
(,'21909','530','1','0','0','-3408.51','795.854','-31.4297','1.45215','30','3','0','2800','0','1');
UPDATE creature_template SET spell1=37918, spell2=37851 WHERE entry=21909;
UPDATE gameobject_template SET ScriptName='go_arcanocontroller' WHERE entry IN (185008, 185009, 185010);

**Comment by tst12** [comment]
before fix https://youtu.be/SUCdZOj-JdE
after fix https://youtu.be/DYsG-Sq5gIs

**Comment by AnonXS** [comment]
```
SELECT * FROM `creature` WHERE `id` IN (21924,21909);
SELECT * FROM `creature_template` WHERE `entry` IN (21924,21909);

DELETE FROM creature  WHERE id=21924;

INSERT IGNORE INTO `creature` (`guid`, `id`, `map`, `spawnMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`) VALUES
(,'21909','530','1','0','0','-3414.29','813.942','-31.1204','1.47848','30','3','0','1','0','1'),
(,'21909','530','1','0','0','-3408.51','795.854','-31.4297','1.45215','30','3','0','2800','0','1');

-- Arcano-Scorp Credit 21924

-- Arcano-Scorp 21909
UPDATE creature_template SET spell1=37918, spell2=37851 WHERE entry=21909;

-- Arcano Control Unit 185008, 185009, 185010
UPDATE gameobject_template SET ScriptName='go_arcanocontroller' WHERE entry IN (185008, 185009, 185010);

```

-- http://db.hellfire-tbc.com/?spell=37919, http://db.hellfire-tbc.com/?spell=37918, http://db.hellfire-tbc.com/?spell=37917

**Comment by Xadras** [comment]
since guidS seems to be missing, could you find out two suitable? :>

**Comment by Xadras** [comment]
Hm currently I'm not sure if its better to redo this to have a clean commit or just merge it for the lulz xD

**Comment by Xadras** [comment]
DELETE FROM creature  WHERE id IN (21909, 21924);

INSERT INTO `creature` (`guid`, `id`, `map`, `spawnMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`) VALUES
(200059, 21909, 530, 1, 0, 0, -3413.58, 828.195, -30.7598, 1.18588, 300, 3, 0, 2800, 0, 1),
('200060','21909','530','1','0','0','-3414.29','813.942','-31.1204','1.47848','300','3','0','2800','0','1'),
('200061','21909','530','1','0','0','-3408.51','795.854','-31.4297','1.45215','300','3','0','2800','0','1');

-- Arcano-Scorp Credit 21924

-- Arcano-Scorp 21909
UPDATE creature_template SET spell1=37918, spell2=37851 WHERE entry=21909;

-- Arcano Control Unit 185008, 185009, 185010
UPDATE gameobject_template SET ScriptName='go_arcanocontroller' WHERE entry IN (185008, 185009, 185010);

**Pull request merged**
